-- SANAD database - schema source of truth
--
-- This file is NOT a runnable schema anymore. It used to be a one-shot
-- "run this in the SQL Editor on a fresh project" script for v0.1, but the
-- database has moved on through 12 migrations since (admin/moderation,
-- volunteer verification, push tokens, avatars, staleness bounds, the full
-- commercial layer, the Jerusalem pilot + i18n support tables, completion
-- confirmation + points, and the security-hardening/index fixes in
-- 0011-0012). Hand-copying all of that into a second file that has to be
-- kept in sync by memory is exactly how this file went stale in the first
-- place - a project bootstrapped from an old copy of this file would come
-- up with NO admin/ban gating, NO volunteer points, NO pilot config, and
-- weaker RLS than what's actually running in production.
--
-- ── Source of truth ──────────────────────────────────────────────────────
--
-- supabase/migrations/*.sql, applied in filename order, is the ONLY
-- accurate description of the schema. To provision a fresh project:
--
--   npx supabase link --project-ref <your-project-ref>
--   npx supabase db push
--
-- This runs every migration in order (0002 through the latest) and leaves
-- you with the exact schema currently running in production - not a
-- point-in-time snapshot that can silently drift.
--
-- To inspect the current schema without applying anything, use Supabase's
-- own dashboard "Database" tab, or (if you have Docker available locally)
-- `npx supabase db dump --linked --schema public`.
--
-- See README.md's "Database" section for the full setup walkthrough,
-- including required storage buckets and the one manual step
-- (public.admin_bootstrap_first_admin()) needed to create the first admin
-- account on a brand new project.
