export const queryKeys = {
  auth: ['auth'] as const,
  profile: (userId: string) => ['profile', userId] as const,
  activeMission: (userId: string) => ['missions', 'active', userId] as const,
  mission: (missionId: string) => ['missions', 'detail', missionId] as const,
  missionEvents: (missionId: string) => ['missions', missionId, 'events'] as const,
  missionMessages: (missionId: string) => ['missions', missionId, 'messages'] as const,
  missionHelperLocation: (missionId: string) => ['missions', missionId, 'helper-location'] as const,
  categories: ['requests', 'categories'] as const,
  scenarios: (categoryId?: string) => ['requests', 'scenarios', categoryId ?? 'all'] as const,
  requesterRequests: (userId: string) => ['requests', 'requester', userId] as const,
  helperRequests: (userId: string) => ['requests', 'helper', userId] as const,
  nearbyRequests: (latitude?: number, longitude?: number) => ['requests', 'nearby', latitude ?? null, longitude ?? null] as const,
  helperProfile: (userId: string) => ['helpers', userId] as const,
  helperSkills: (userId: string) => ['helpers', userId, 'skills'] as const,
  businesses: (market: string) => ['community', 'businesses', market] as const,
  business: (id: string) => ['community', 'business', id] as const,
  offers: (market: string) => ['community', 'offers', market] as const,
  offer: (id: string) => ['community', 'offer', id] as const,
  membership: (userId: string) => ['community', 'membership', userId] as const,
  rewards: (market: string) => ['rewards', 'catalog', market] as const,
  points: (userId: string) => ['rewards', 'points', userId] as const,
  redemptions: (userId: string) => ['rewards', 'redemptions', userId] as const,
  activity: (userId: string) => ['activity', userId] as const,
  devices: (userId: string) => ['devices', userId] as const,
  notifications: (userId: string) => ['notifications', userId] as const,
  reports: (userId: string) => ['safety', 'reports', userId] as const,
  blocks: (userId: string) => ['safety', 'blocks', userId] as const
}
