import { useTranslation } from 'react-i18next'
import type { LocalizedText, V2Language } from '../domain/v2'

const copy = {
  'brand.name': { ar: 'سَنَد', he: 'סָנָד', en: 'SANAD' },
  'brand.promise': { ar: 'القدس تسند بعضها', he: 'ירושלים תומכת זו בזו', en: 'Jerusalem supports one another' },
  'common.back': { ar: 'رجوع', he: 'חזרה', en: 'Back' },
  'common.continue': { ar: 'متابعة', he: 'המשך', en: 'Continue' },
  'common.cancel': { ar: 'إلغاء', he: 'ביטול', en: 'Cancel' },
  'common.save': { ar: 'حفظ', he: 'שמירה', en: 'Save' },
  'common.retry': { ar: 'إعادة المحاولة', he: 'ניסיון חוזר', en: 'Try again' },
  'common.close': { ar: 'إغلاق', he: 'סגירה', en: 'Close' },
  'common.notEmergency': { ar: 'سَنَد للمساندة المجتمعية غير الطارئة', he: 'סָנָד מיועד לסיוע קהילתי שאינו חירום', en: 'SANAD is for non-emergency community assistance' },
  'language.title': { ar: 'اختر لغتك', he: 'בחירת שפה', en: 'Choose your language' },
  'language.subtitle': { ar: 'يمكنك تغييرها لاحقاً من الإعدادات', he: 'אפשר לשנות אחר כך בהגדרות', en: 'You can change this later in Settings' },
  'language.ar': { ar: 'العربية', he: 'ערבית', en: 'Arabic' },
  'language.he': { ar: 'العبرية', he: 'עברית', en: 'Hebrew' },
  'language.en': { ar: 'الإنجليزية', he: 'אנגלית', en: 'English' },
  'welcome.kicker': { ar: 'شبكة مساندة مدنية', he: 'רשת סיוע אזרחית', en: 'CIVIC SUPPORT NETWORK' },
  'welcome.title': { ar: 'المساندة الأقرب، عندما تحتاجها', he: 'העזרה הקרובה, כשצריך אותה', en: 'Nearby support, when you need it' },
  'welcome.body': { ar: 'اطلب مساندة آمنة أو ساعد شخصاً قريباً منك في القدس.', he: 'בקשו סיוע בטוח או עזרו למישהו קרוב בירושלים.', en: 'Request safe assistance or help someone nearby in Jerusalem.' },
  'welcome.login': { ar: 'تسجيل الدخول', he: 'כניסה', en: 'Sign in' },
  'welcome.create': { ar: 'إنشاء حساب', he: 'יצירת חשבון', en: 'Create account' },
  'auth.loginTitle': { ar: 'أهلاً بعودتك', he: 'טוב שחזרת', en: 'Welcome back' },
  'auth.loginBody': { ar: 'ادخل إلى شبكة سَنَد الآمنة', he: 'כניסה לרשת הבטוחה של סָנָד', en: 'Sign in to your trusted SANAD network' },
  'auth.email': { ar: 'البريد الإلكتروني', he: 'דוא״ל', en: 'Email address' },
  'auth.password': { ar: 'كلمة المرور', he: 'סיסמה', en: 'Password' },
  'auth.fullName': { ar: 'الاسم الكامل', he: 'שם מלא', en: 'Full name' },
  'auth.phone': { ar: 'رقم الهاتف', he: 'מספר טלפון', en: 'Phone number' },
  'auth.loginAction': { ar: 'دخول آمن', he: 'כניסה בטוחה', en: 'Continue securely' },
  'auth.forgot': { ar: 'نسيت كلمة المرور؟', he: 'שכחת סיסמה?', en: 'Forgot password?' },
  'auth.signupTitle': { ar: 'أنشئ هويتك في سَنَد', he: 'יצירת הזהות שלך בסָנָד', en: 'Create your SANAD identity' },
  'auth.signupBody': { ar: 'معلومات واضحة تبني الثقة بين أفراد المجتمع', he: 'פרטים ברורים בונים אמון בקהילה', en: 'Clear information builds trust across the community' },
  'auth.signupAction': { ar: 'إنشاء الحساب', he: 'יצירת החשבון', en: 'Create account' },
  'auth.verifyTitle': { ar: 'تحقق من بريدك', he: 'בדיקת הדוא״ל', en: 'Check your email' },
  'auth.verifyBody': { ar: 'أرسلنا رابط تأكيد. افتحه للعودة إلى سَنَد.', he: 'שלחנו קישור לאישור. פתחו אותו כדי לחזור לסָנָד.', en: 'We sent a confirmation link. Open it to return to SANAD.' },
  'auth.resend': { ar: 'إعادة إرسال الرابط', he: 'שליחה מחדש', en: 'Resend link' },
  'auth.forgotTitle': { ar: 'استعادة كلمة المرور', he: 'שחזור סיסמה', en: 'Reset your password' },
  'auth.forgotBody': { ar: 'سنرسل رابطاً آمناً إلى بريدك', he: 'נשלח קישור מאובטח לדוא״ל', en: 'We will email you a secure reset link' },
  'auth.sendLink': { ar: 'إرسال الرابط', he: 'שליחת קישור', en: 'Send reset link' },
  'auth.resetTitle': { ar: 'كلمة مرور جديدة', he: 'סיסמה חדשה', en: 'Choose a new password' },
  'auth.sessionExpired': { ar: 'انتهت جلستك', he: 'פג תוקף החיבור', en: 'Your session expired' },
  'auth.sessionExpiredBody': { ar: 'سجل الدخول مجدداً لحماية حسابك.', he: 'יש להתחבר שוב כדי להגן על החשבון.', en: 'Sign in again to protect your account.' },
  'auth.offlineTitle': { ar: 'أنت غير متصل', he: 'אין חיבור לרשת', en: 'You are offline' },
  'auth.offlineBody': { ar: 'الاتصال مطلوب لتسجيل الدخول بأمان.', he: 'נדרש חיבור כדי להיכנס בבטחה.', en: 'A connection is required to sign in securely.' },
  'auth.restrictedTitle': { ar: 'الحساب مقيّد', he: 'החשבון מוגבל', en: 'Account restricted' },
  'auth.restrictedBody': { ar: 'لا يمكن استخدام المهام حالياً. تواصل مع فريق الأمان.', he: 'לא ניתן להשתמש במשימות כעת. פנו לצוות הבטיחות.', en: 'Missions are unavailable right now. Contact the safety team.' },
  'tabs.home': { ar: 'الرئيسية', he: 'בית', en: 'Home' },
  'tabs.community': { ar: 'المجتمع', he: 'קהילה', en: 'Community' },
  'tabs.activity': { ar: 'النشاط', he: 'פעילות', en: 'Activity' },
  'tabs.account': { ar: 'الحساب', he: 'חשבון', en: 'Account' },
  'home.greeting': { ar: 'مساء الخير', he: 'ערב טוב', en: 'Good evening' },
  'home.title': { ar: 'كيف يمكن أن نتساند اليوم؟', he: 'איך אפשר לתמוך היום?', en: 'How can we support one another today?' },
  'home.need': { ar: 'أحتاج مساندة', he: 'אני צריך עזרה', en: 'I need help' },
  'home.needBody': { ar: 'أنشئ طلباً واضحاً وآمناً', he: 'יצירת בקשה ברורה ובטוחה', en: 'Create a clear, safe request' },
  'home.help': { ar: 'أستطيع المساندة', he: 'אני יכול לעזור', en: 'I can help' },
  'home.helpBody': { ar: 'شاهد الاحتياجات القريبة منك', he: 'צפייה בצרכים קרובים', en: 'See needs near you' },
  'home.active': { ar: 'مهمة نشطة', he: 'משימה פעילה', en: 'Active mission' },
  'home.resume': { ar: 'متابعة المهمة', he: 'המשך המשימה', en: 'Resume mission' },
  'home.emergency': { ar: 'هل هناك خطر فوري؟', he: 'יש סכנה מיידית?', en: 'Is someone in immediate danger?' },
  'home.emergencyBody': { ar: 'اتصل بخدمات الطوارئ الرسمية. لا تنتظر متطوعاً.', he: 'יש לפנות לשירותי החירום הרשמיים ולא להמתין למתנדב.', en: 'Contact official emergency services. Do not wait for a volunteer.' },
  'home.emergencyAction': { ar: 'عرض خيارات الطوارئ', he: 'אפשרויות חירום', en: 'View emergency options' },
  'request.screenTitle': { ar: 'فحص الأمان أولاً', he: 'קודם בודקים בטיחות', en: 'Safety check first' },
  'request.screenBody': { ar: 'أجب بصدق لنوجّهك إلى المساعدة الصحيحة.', he: 'ענו בכנות כדי שנכוון לעזרה הנכונה.', en: 'Answer honestly so we can guide you to the right help.' },
  'request.danger': { ar: 'يوجد خطر فوري على شخص', he: 'יש סכנה מיידית לאדם', en: 'Someone is in immediate danger' },
  'request.medical': { ar: 'حالة طبية طارئة', he: 'מצב רפואי דחוף', en: 'There is a medical emergency' },
  'request.fireViolence': { ar: 'حريق أو عنف أو تهديد', he: 'שריפה, אלימות או איום', en: 'Fire, violence, or a threat' },
  'request.vulnerable': { ar: 'طفل أو شخص ضعيف معرّض للخطر', he: 'ילד או אדם פגיע נמצא בסיכון', en: 'A child or vulnerable person is at risk' },
  'request.safeContinue': { ar: 'لا شيء مما سبق — متابعة', he: 'אף אחד מאלה — המשך', en: 'None of these — continue' },
  'request.handoffTitle': { ar: 'هذه حالة طارئة', he: 'זהו מצב חירום', en: 'This needs emergency services' },
  'request.handoffBody': { ar: 'سَنَد لا يستبدل الإسعاف أو الشرطة أو الإطفاء. انتقل إلى مكان آمن واتصل فوراً.', he: 'סָנָד אינו מחליף מד״א, משטרה או כבאות. עברו למקום בטוח והתקשרו עכשיו.', en: 'SANAD does not replace ambulance, police, or fire services. Move somewhere safe and call now.' },
  'request.categoryTitle': { ar: 'ما نوع المساندة؟', he: 'איזו עזרה נדרשת?', en: 'What kind of support?' },
  'request.categoryBody': { ar: 'اختر الأقرب إلى احتياجك', he: 'בחרו את האפשרות הקרובה ביותר לצורך', en: 'Choose the closest match' },
  'request.scenarioTitle': { ar: 'اختر السيناريو', he: 'בחירת מצב', en: 'Choose a scenario' },
  'request.detailsTitle': { ar: 'اشرح ما تحتاجه', he: 'תיאור הצורך', en: 'Tell us what you need' },
  'request.detailsBody': { ar: 'اكتب معلومات مفيدة، ولا تضف بيانات حساسة.', he: 'כתבו מידע שימושי בלי פרטים רגישים.', en: 'Share useful context without sensitive information.' },
  'request.detailsPlaceholder': { ar: 'مثال: أحتاج شخصاً لاستلام الدواء من الصيدلية القريبة…', he: 'לדוגמה: צריך מישהו שיאסוף תרופה מבית המרקחת הקרוב…', en: 'Example: I need someone to collect medicine from the nearby pharmacy…' },
  'request.mediaTitle': { ar: 'أضف صورة عند الحاجة', he: 'הוספת תמונה במידת הצורך', en: 'Add a photo if useful' },
  'request.mediaBody': { ar: 'سنحمي الوسائط ونشاركها فقط مع أطراف المهمة.', he: 'המדיה תוגן ותשותף רק עם משתתפי המשימה.', en: 'Media is protected and shared only with mission participants.' },
  'request.addPhoto': { ar: 'إضافة صورة', he: 'הוספת תמונה', en: 'Add photo' },
  'request.locationTitle': { ar: 'أين تحتاج المساندة؟', he: 'איפה נדרשת העזרה?', en: 'Where is help needed?' },
  'request.locationBody': { ar: 'راجع الموقع الدقيق قبل المتابعة', he: 'בדקו את המיקום המדויק לפני ההמשך', en: 'Confirm the exact location before continuing' },
  'request.useLocation': { ar: 'استخدام موقعي الحالي', he: 'שימוש במיקום הנוכחי', en: 'Use my current location' },
  'request.reviewTitle': { ar: 'راجع طلبك', he: 'בדיקת הבקשה', en: 'Review your request' },
  'request.publish': { ar: 'إرسال طلب المساندة', he: 'שליחת בקשת העזרה', en: 'Send help request' },
  'request.matchingTitle': { ar: 'نبحث في شبكة سَنَد', he: 'מחפשים ברשת סָנָד', en: 'Searching the SANAD network' },
  'request.matchingBody': { ar: 'سننبه المساندين المناسبين والقريبين.', he: 'נעדכן מסייעים מתאימים וקרובים.', en: 'We are notifying suitable nearby helpers.' },
  'request.assignedTitle': { ar: 'تم تعيين مساند', he: 'נמצא מסייע', en: 'A helper is assigned' },
  'helper.onboardingTitle': { ar: 'كن مسانداً موثوقاً', he: 'להיות מסייע מהימן', en: 'Become a trusted helper' },
  'helper.onboardingBody': { ar: 'اختر ما تستطيع فعله، واللغات التي تتحدثها، وحدودك بوضوح.', he: 'בחרו יכולות, שפות וגבולות ברורים.', en: 'Choose your skills, languages, and boundaries clearly.' },
  'helper.skillsTitle': { ar: 'مهارات المساندة', he: 'כישורי סיוע', en: 'Support skills' },
  'helper.languagesTitle': { ar: 'لغات التواصل', he: 'שפות תקשורת', en: 'Communication languages' },
  'helper.availabilityTitle': { ar: 'وضع المساندة', he: 'מצב סיוע', en: 'Help mode' },
  'helper.availabilityBody': { ar: 'أنت تتحكم بوقت ظهورك وموقعك.', he: 'אתם שולטים בזמינות ובשיתוף המיקום.', en: 'You control when you are visible and share location.' },
  'helper.goOnline': { ar: 'بدء التوفر', he: 'מעבר לזמין', en: 'Go available' },
  'helper.goOffline': { ar: 'إيقاف التوفر', he: 'הפסקת זמינות', en: 'Stop availability' },
  'helper.nearbyTitle': { ar: 'طلبات قريبة', he: 'בקשות קרובות', en: 'Nearby requests' },
  'helper.nearbyBody': { ar: 'اختر فقط مهمة مناسبة لمهاراتك ووقتك.', he: 'בחרו רק משימה שמתאימה לכישורים ולזמן.', en: 'Choose only a mission that fits your skills and time.' },
  'helper.requestDetails': { ar: 'تفاصيل الطلب', he: 'פרטי הבקשה', en: 'Request details' },
  'helper.accept': { ar: 'قبول المهمة', he: 'קבלת המשימה', en: 'Accept mission' },
  'mission.live': { ar: 'مهمة مباشرة', he: 'משימה בזמן אמת', en: 'LIVE MISSION' },
  'mission.navigate': { ar: 'فتح الملاحة', he: 'פתיחת ניווט', en: 'Open navigation' },
  'mission.call': { ar: 'اتصال', he: 'שיחה', en: 'Call' },
  'mission.message': { ar: 'محادثة', he: 'שיחה כתובה', en: 'Conversation' },
  'mission.arrived': { ar: 'وصلت إلى الموقع', he: 'הגעתי למקום', en: 'I have arrived' },
  'mission.start': { ar: 'بدء المساندة', he: 'התחלת הסיוע', en: 'Start assistance' },
  'mission.complete': { ar: 'إنهاء المهمة', he: 'סיום המשימה', en: 'Complete mission' },
  'mission.safety': { ar: 'أدوات الأمان', he: 'כלי בטיחות', en: 'Safety tools' },
  'mission.dispute': { ar: 'الاعتراض على الإنهاء', he: 'מחלוקת על הסיום', en: 'Dispute completion' },
  'mission.report': { ar: 'إبلاغ فريق الأمان', he: 'דיווח לצוות הבטיחות', en: 'Report to safety team' },
  'mission.block': { ar: 'حظر المستخدم', he: 'חסימת המשתמש', en: 'Block user' },
  'mission.ratingTitle': { ar: 'كيف كانت التجربة؟', he: 'איך הייתה החוויה?', en: 'How was the experience?' },
  'mission.ratingBody': { ar: 'يساعد تقييمك في بناء شبكة أكثر أماناً.', he: 'הדירוג עוזר לבנות רשת בטוחה יותר.', en: 'Your feedback helps build a safer network.' },
  'mission.completedTitle': { ar: 'اكتملت المساندة', he: 'הסיוע הושלם', en: 'Support completed' },
  'community.title': { ar: 'المجتمع', he: 'קהילה', en: 'Community' },
  'community.body': { ar: 'خدمات موثوقة ومكافآت تعيد القيمة إلى المجتمع', he: 'שירותים מהימנים ותגמולים שמחזירים ערך לקהילה', en: 'Trusted services and rewards that return value to the community' },
  'community.businesses': { ar: 'المصالح', he: 'עסקים', en: 'Businesses' },
  'community.offers': { ar: 'العروض', he: 'הטבות', en: 'Offers' },
  'community.plus': { ar: 'سَنَد+', he: 'סָנָד+', en: 'SANAD+' },
  'community.rewards': { ar: 'المكافآت', he: 'תגמולים', en: 'Rewards' },
  'community.points': { ar: 'سجل النقاط', he: 'היסטוריית נקודות', en: 'Points history' },
  'community.search': { ar: 'ابحث عن مصلحة أو خدمة', he: 'חיפוש עסק או שירות', en: 'Search businesses and services' },
  'community.noBusinesses': { ar: 'لا توجد مصالح متاحة حالياً', he: 'אין עסקים זמינים כרגע', en: 'No businesses are available right now' },
  'community.noOffers': { ar: 'لا توجد عروض متاحة حالياً', he: 'אין הטבות זמינות כרגע', en: 'No offers are available right now' },
  'activity.title': { ar: 'نشاطك في سَنَد', he: 'הפעילות שלך בסָנָד', en: 'Your SANAD activity' },
  'activity.all': { ar: 'الكل', he: 'הכול', en: 'All' },
  'activity.received': { ar: 'تلقيت مساندة', he: 'קיבלתי עזרה', en: 'Help received' },
  'activity.given': { ar: 'قدّمت مساندة', he: 'עזרתי', en: 'Help given' },
  'activity.empty': { ar: 'سيظهر نشاطك هنا', he: 'הפעילות תופיע כאן', en: 'Your activity will appear here' },
  'account.title': { ar: 'حسابك', he: 'החשבון שלך', en: 'Your account' },
  'account.profile': { ar: 'الملف الشخصي', he: 'פרופיל', en: 'Profile' },
  'account.settings': { ar: 'الإعدادات', he: 'הגדרות', en: 'Settings' },
  'account.language': { ar: 'اللغة والاتجاه', he: 'שפה וכיוון', en: 'Language and direction' },
  'account.privacy': { ar: 'الخصوصية والأذونات', he: 'פרטיות והרשאות', en: 'Privacy and permissions' },
  'account.notifications': { ar: 'الإشعارات', he: 'התראות', en: 'Notifications' },
  'account.accessibility': { ar: 'إمكانية الوصول', he: 'נגישות', en: 'Accessibility' },
  'account.safety': { ar: 'مركز الأمان', he: 'מרכז בטיחות', en: 'Safety center' },
  'account.support': { ar: 'الدعم', he: 'תמיכה', en: 'Support' },
  'account.logout': { ar: 'تسجيل الخروج', he: 'יציאה', en: 'Sign out' },
  'state.loading': { ar: 'جارٍ التحميل…', he: 'טוען…', en: 'Loading…' },
  'state.offline': { ar: 'لا يوجد اتصال بالإنترنت', he: 'אין חיבור לאינטרנט', en: 'No internet connection' },
  'state.error': { ar: 'تعذر تحميل هذه الصفحة', he: 'לא ניתן לטעון את הדף', en: 'We could not load this screen' }
} satisfies Record<string, LocalizedText>

export type V2CopyKey = keyof typeof copy

export function v2Text(key: V2CopyKey, language: string): string {
  const value = copy[key]
  return value[language as V2Language] ?? value.ar
}

export function useV2Text() {
  const { i18n } = useTranslation()
  return (key: V2CopyKey) => v2Text(key, i18n.language)
}

export { copy as v2Copy }
